name: Install Chrome and run npm script

on:
  push:
    branches:
      - main

jobs:
  install_chrome_and_run_npm_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Chrome
      uses: actions/setup-chrome@v1
      with:
        chrome-version: latest

    - name: Install dependencies
      run: |
        npm ci

    - name: Run npm script
      run: |
        npm run wdio
